### ISSUE TITLE
An error happened when I used 'xlrd' to read excel file

### ISSUE THREAD

**Issue by HUSTlwr** [exodrifter/unity-python#27]
I'm sorry to disturb you again and thank you first. There are codes that I wrote to read the excel file:
```cs
var engine = global::UnityPython.CreateEngine(); 
var scope = engine.CreateScope();
var paths = engine.GetSearchPaths();
paths.Add(UnityEngine.Application.dataPath + "/UsePythonInUnity/Lib");
engine.SetSearchPaths(paths);
string code = "";
code += "import xlrd" + "\n";
code += "file = 'test.xlsx'" + "\n";
code += "file = file.decode('utf-8')" + "\n";
code += "filename = str(file)" + "\n";
code += "excelfile = xlrd.open_workbook(filename)" + "\n";
code += "sheet1 = excelfile.sheet_by_index(1)" + "\n";
code += "row = sheet1.row_values(1)" + "\n";
code += "line = ''.join('%s' %id for id in row)" + "\n";
var source = engine.CreateScriptSourceFromString(code);
string result = scope.GetVariable<string>("line");
```

The error info：
`Microsoft.Scripting.ArgumentTypeException: expected str, got bytes`

![2e5fa5b37a5790d6568218bf2cc1b99](https://user-images.githubusercontent.com/50614735/79562069-fb918580-80dc-11ea-9d3d-90f67b03a7ff.png)

I tried to cut down my python codes line by line, and I found the same error happened even if I just used first five lines python codes. But if I just used first four lines python codes, no error would happen. Since I thought the error happened in fifth line python code:
`code += "excelfile = xlrd.open_workbook(filename)" + "\n";`

But I have checked the type of the variable 'filename' by using 'type()' function, so I can confirm that the type of variable 'filename' is 'str'. Consequently, this error confusing me a lot and I have no idea about the cause of this error. I wuold appreciate it if you can provide some clues. Thanks again!

**Comment by exodrifter** [comment]
A [stackoverflow post](https://stackoverflow.com/a/16576274) suggests that IronPython's strings are Unicode by default, which causes `open_workbook` to fail because it requires the filename to be a byte string. Doing the following should fix the problem:

```py
xlrd.open_workbook(bytes(filename))
```

If this doesn't work, could you please upload a minimal project that reproduces the issue? It would save a lot of time and make it easier to find a solution to the problem.

**Comment by HUSTlwr** [comment]
I have tried following:
`xlrd.open_workbook(bytes(filename))`
But it didn't work. So, I uploaded a minimal project. I wrote a script to read Excel by using python and the script was attched to the 'Button'.

**Comment by HUSTlwr** [comment]
[PythonReadExcel.zip](https://github.com/exodrifter/unity-python/files/4493399/PythonReadExcel.zip)

**Comment by HUSTlwr** [comment]
Emmm, the above one seems cannot be downloaded. Try this one.
[PythonReadExcel.zip](https://github.com/exodrifter/unity-python/files/4495943/PythonReadExcel.zip)

**Comment by exodrifter** [comment]
It looks like the error is caused by line 53 in the `xlsx.py` file in the xlrd source code. You'll need to change this line...
```py
_dummy_stream = BYTES_IO(b'')
```
...to this:
```py
_dummy_stream = BYTES_IO('')
```

It might be that the IronPython release that we're using has a bug in it, since the [Python 2.7 documentation](https://docs.python.org/2.7/reference/lexical_analysis.html#string-literals) states:
> A prefix of 'b' or 'B' is ignored in Python 2; it indicates that the literal should become a bytes literal in Python 3 (e.g. when code is automatically converted with 2to3).

IronPython might be doing the Python 3 behavior here (converting the string to bytes) when it should really be doing what Python 2.7 would do (using the string as a string). I will file a bug report with IronPython unless this is fixed in a newer version or if there is some stated reason for why IronPython behaves this way.

On the other hand, it also makes it seem like there is a bug in xlrd since it seems like this would break in Python 3. However, filing a bug report with xlrd would be pointless since it no longer has any maintainers. [As per the suggestion on the xlrd README](https://github.com/python-excel/xlrd/tree/f8371f009fe535795d1452ef0de2ee041b305dac#xlrd), I would suggest moving to a new library that _is_ maintained, such as openpyxl.

**Comment by exodrifter** [comment]
Upon further research, it looks like this is a known issue: IronLanguages/ironpython2#568

**Comment by HUSTlwr** [comment]
The '.xlsx' file still cannot be read normally after I modified 'xlsx.py'. And I intended to try openpyxl. Anyway, I appreciate your helping me.
